bunn-*-content: add missing variable to dataModel.js
Missing definition of var res resulted in:

file:///application/bin/content/js/dataModel.js:196: Error: Invalid write to global property "res"

Signed-off-by: Steve Sakoman <steve@sakoman.com>